---
title: "$ e mais fatores nos votos de 2014"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(viridis)

library(broom)
library(modelr)

source(here::here("code/lib.R"))
theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = FALSE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r read}
dados = read_projectdata()

dados = dados %>% 
    mutate(votos_log = log10(votos), 
           gastos_log = log10(total_despesa))
```

```{r}
dados %>% 
    ggplot(aes(x = idade, y = votos_prop)) + 
    geom_point(size = .5, alpha = .4) + 
    scale_y_log10()
```

```{r}
dados %>% 
    ggplot(aes(x = sexo, y = votos)) + 
    geom_boxplot() + 
    scale_y_log10()
```

## Regressões

### Votos ~ Sexo

```{r}

```

### Votos ~ Sexo + Idade


### Votos ~ Sexo + Idade + $